### ISSUE TITLE
Incompatible with phospor

### ISSUE THREAD

**Issue by wassupiamYusuf** [Red-Studio-Ragnarok/Red-Core#20]
When I use phospor with the mod the game crashes
Minecraft version 1.12.2
Forge version 14.23.5.2859
Crash logs
---- Minecraft Crash Report ----

WARNING: coremods are present:
  RenderLibPlugin (RenderLib-1.12.2-1.3.5.jar)
  PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  Modern Warfare Cubed Plugin (Modern-Warfare-Cubed-0.1.7.jar)
  NothiriumPlugin (Nothirium-1.12.2-0.3.4-beta.jar)
  Red Core (!Red-Core-MC-1.7-1.12-0.5.1.jar)
  MixinBooter (!mixinbooter-9.1.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 7/9/24 9:36 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraft/world/chunk/Chunk
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.common.ForgeModContainer.preInit(ForgeModContainer.java:495)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraft.world.chunk.Chunk
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 43 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:406)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:240)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:71)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method setBlockStateInjectGenerateSkylightMapVanilla(Z)Z in mixins.phosphor.json:common.MixinChunk$Vanilla from mod unknown-owner failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.phosphor.refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1384)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:377)
	... 50 more

(MixinBooter) Mixins in Stacktrace:
	net/minecraft/world/chunk/Chunk:
		meldexun.renderlib.mixin.MixinChunk (mixins.renderlib.json) [unknown-location]
		me.jellysquid.mods.phosphor.mixins.lighting.common.MixinChunk$Vanilla (mixins.phosphor.json) [unknown-location]
		me.jellysquid.mods.phosphor.mixins.lighting.common.MixinChunk (mixins.phosphor.json) [unknown-location]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.getConstructor(Class.java:1825)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:128)
	at net.minecraftforge.fml.common.eventhandler.EventBus.register(EventBus.java:112)
	at net.minecraftforge.common.ForgeModContainer.preInit(ForgeModContainer.java:495)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 991231912 bytes (945 MB) / 1275068416 bytes (1216 MB) up to 3154116608 bytes (3008 MB)
	JVM Flags: 7 total; -Xmx3000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 14 mods loaded, 14 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                         | Version      | Source                                      | Signature                                |
	|:----- |:-------------------------- |:------------ |:------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                  | 1.12.2       | minecraft.jar                               | None                                     |
	| LCH   | mcp                        | 9.42         | minecraft.jar                               | None                                     |
	| LCH   | FML                        | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                      | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar               | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | mixinbooter                | 9.1          | minecraft.jar                               | None                                     |
	| LC    | redcore                    | 0.5.1        | !Red-Core-MC-1.7-1.12-0.5.1.jar             | None                                     |
	| LC    | battletowers               | 1.6.5        | BattleTowers-1.12.2.jar                     | None                                     |
	| LC    | ichunutil                  | 7.2.2        | iChunUtil-1.12.2-7.2.2.jar                  | 4db5c2bd1b556f252a5b8b54b256d381b2a0a6b8 |
	| LC    | mobdismemberment           | 7.0.0        | MobDismemberment-1.12.2-7.0.0.jar           | None                                     |
	| LC    | mwc                        | 0.1.7        | Modern-Warfare-Cubed-0.1.7.jar              | None                                     |
	| LC    | renderlib                  | 1.3.5        | RenderLib-1.12.2-1.3.5.jar                  | None                                     |
	| LC    | nothirium                  | 0.3.4-beta   | Nothirium-1.12.2-0.3.4-beta.jar             | None                                     |
	| LC    | tlauncher_custom_cape_skin | 1.4          | tlskincape1.12.2-1.4.jar                    | None                                     |
	| LC    | phosphor-lighting          | 1.12.2-0.2.6 | phosphor-1.12.2-0.2.6+build50-universal.jar | f0387d288626cc2d937daa504e74af570c52a2f1 |

	Loaded coremods (and transformers): 
RenderLibPlugin (RenderLib-1.12.2-1.3.5.jar)
  meldexun.renderlib.asm.RenderLibClassTransformer
PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
  
TLSkinCapeHookLoader (tlskincape1.12.2-1.4.jar)
  gloomyfolken.hooklib.minecraft.PrimaryClassTransformer
Modern Warfare Cubed Plugin (Modern-Warfare-Cubed-0.1.7.jar)
  com.paneedah.mwc.asm.MWCClassTransformer
NothiriumPlugin (Nothirium-1.12.2-0.3.4-beta.jar)
  meldexun.nothirium.mc.asm.NothiriumClassTransformer
Red Core (!Red-Core-MC-1.7-1.12-0.5.1.jar)
  
MixinBooter (!mixinbooter-9.1.jar)
  
	GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 24.20.100.6292' Renderer: 'Intel(R) HD Graphics 620'
	Launched Version: IDK
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 620 GL version 4.5.0 - Build 24.20.100.6292, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz

**Comment by Desoroxxx** [comment]
Just use Alfheim Lightning Engine
